AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - '**/*.gemspec'
    - '**/vendor/bundle/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
